### ISSUE TITLE
Confusion between reset! and setstate!

### ISSUE THREAD

**Issue by klowrey** [Lyceum/LyceumMuJoCo.jl#3]
lyceummujoco exposes `setstate!(env, s)` while lyceum base has a `reset!(env, s)` function. Their functionality seems to be generally the same: put the sim in a particular state `s`.

notably, LyceumAI's mppi function uses `reset!(env, s)` to reset the environment to a particular state; if `length(s) != length(env.sim.initstate)` there are problems. In this case setstate and reset functionally are the same.

If they are always the same, we should get rid of one of them.

**Comment by colinxs** [comment]
fixed in Lyceum/LyceumBase.jl#7
