### ISSUE TITLE
Saving and Loading of experiments

### ISSUE THREAD

**Issue by klowrey** [Lyceum/LyceumMuJoCo.jl#5]
We want to save more into jlso's:

Save experiment data
save the environment file at that time
save the loaded model file at that time (and meshes? or could symlink...)
save policy, value function, etc.

Then load it all. At least for a visualizer to bring it back. A big reason for this is to run an experiment on a bigger machine, then copy back the jlso onto your local host for rendering; it's annoying to sync the code repos to load the env...

**Comment by colinxs** [comment]
closed in favor of Lyceum/LyceumBase.jl#5
